export const jobCategories = [
  "Office",
  "Driver",
  "Dispatcher",
  "Cleaning",
  "Beauty Salon",
  "Sales/Retail",
  "IT/Programming",
  "Marketing",
  "Design",
  "Construction",
  "Repair",
  "Warehouses/Factories",
  "Pharmacy",
  "Jobs For Students",
  "Legal/Notaries",
];
