export const allPrices = [
  {
    id: 1,
    name: "Video Advertisement",
    price: "90",
    expires: "30",
    stripe_link: "https://buy.stripe.com/fZeeYM9xfbpq6aIfZ5",
    location_image_link: "/locationsForAdTypes/VideoAds.png",
  },
  {
    id: 2,
    name: "Top Banner Advertisement",
    price: "70",
    expires: "30",
    stripe_link: "https://buy.stripe.com/eVacQEcJr512fLi3ci",
    location_image_link: "/locationsForAdTypes/BannerAds.png",
  },
  {
    id: 3,
    name: "Side Small Image Advertisement",
    price: "50",
    expires: "30",
    stripe_link: "https://buy.stripe.com/00gcQE4cV0KM0QodQV",
    location_image_link: "/locationsForAdTypes/SideAds.png",
  },
  {
    id: 4,
    name: "Running Sentence Advertisement",
    price: "25",
    expires: "10",
    stripe_link: "https://buy.stripe.com/9AQaIweRz0KMeHefZ2",
    location_image_link: "/locationsForAdTypes/RunningAds.png",
  },
  {
    id: 5,
    name: "Special Listing (Will be visible on Homepage & with regular listings)",
    price: "15",
    expires: "30",
    stripe_link: "https://buy.stripe.com/4gw8Ao24NfFGgPmaEH",
  },
  {
    id: 6,
    name: "Regular Listing (Will NOT be visible on Homepage)",
    price: "5",
    expires: "30",
    stripe_link: "https://buy.stripe.com/00g9EsaBjbpq2Yw7su",
  },
];
