export const serviceTypes = [
  "Consulting",
  "Customer Service",
  "Human Resources",
  "Gardeners",
  "Janitors",
  "Mechanics",
  "Body Shop",
  "Carpentry",
  "Electricians",
  "Plumbing",
  "Death Care",
  "Funeral Homes",
  "Diplomacy",
  "Incarceration",
  "Lawyers",
  "Entertainment",
  "Sport",
  "Television",
  "Fabric Care",
  "Dry Cleaning",
  "Laundry",
  "Accountancy",
  "Real Estate",
  "Stock Brokerages",
  "Tax Services",
  "Health Care",
  "Information Services",
  "Interpreting",
  "Translation",
  "Body Hair Removal",
  "Dental",
  "Hairdressing",
  "Manicure / Pedicure",
  "Insurance",
  "Security",
  "Social Services",
  "Childcare",
  "Elderly Care",
  "Transport",
  "Warehousing",
  "Stock Management",
  "Packaging",
  "Driving",
  "Construction",
  "Furniture Repair",
  "Windows / Doors",
  "Moving",
  "Media",
  "Design",
  "Tutoring",
  "Languages",
  "Appliance Repair",
  "House Cleaning",
  "Catering",
  "Video / Photography",
  "Events",
  "Travel / Tourism",
  "Shipping",
];
