import React, { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import PageHeader from "../components/Reusable/PageHeader";
import DisplayListings from "../components/Reusable/DisplayListings";

export default function Home() {
  const [sellingSpecialHouses, setSellingSpecialHouses] = useState([]);
  const [rentingSpecialHouses, setRentingSpecialHouses] = useState([]);

  const [specialJobs, setSpecialJobs] = useState([]);

  useEffect(() => {
    let isMounted = true;
    // stex fetcherna arvelu
    fetch(
      `${process.env.NEXT_PUBLIC_LINK_TO_FETCH}/get-houses-for-sale?is_special=true`
    )
      .then((response) => response.json())
      .then((data) => {
        if (data.msg) {
          console.log(data.msg);
        } else {
          if (isMounted) {
            setSellingSpecialHouses(data.specialHousesForSale);
          }
        }
      });

    fetch(`${process.env.NEXT_PUBLIC_LINK_TO_FETCH}/get-jobs?is_special=true`)
      .then((response) => response.json())
      .then((data) => {
        if (data.msg) {
          console.log(data.msg);
        } else {
          if (isMounted) {
            setSpecialJobs(data.specialJobs);
          }
        }
      });
    return () => {
      isMounted = false;
    };
  }, []);

  return (
    <div className={styles.homepage_container}>
      {/* to be changed later */}
      <PageHeader
        title="Home Page | Listing Website"
        description="description"
        content="Generated by create next app"
        iconLink="/favicon.ico"
      />
      {specialJobs.length ? (
        <DisplayListings
          containerTitle="Boosted Jobs"
          itemsToDisplay={specialJobs}
          amountOfItemsToDisplay={10}
          areWithoutImage={true}
        />
      ) : null}
      {sellingSpecialHouses.length ? (
        <DisplayListings
          containerTitle="Houses for Sale"
          itemsToDisplay={sellingSpecialHouses}
          amountOfItemsToDisplay={10}
        />
      ) : null}
    </div>
  );
}
