import React, { useState, useEffect } from "react";
import styles from "../styles/Home.module.css";
import PageHeader from "../components/Reusable/PageHeader";
import DisplayListings from "../components/Reusable/DisplayListings";
import { sortArrayInDescendingOrder } from "../components/UsefulFunctions/helperFunctions";

export default function Home() {
  const [sellingSpecialHouses, setSellingSpecialHouses] = useState([]);
  const [rentingSpecialHouses, setRentingSpecialHouses] = useState([]);

  const [specialJobs, setSpecialJobs] = useState([]);

  useEffect(() => {
    let isMounted = true;
    // stex fetcherna arvelu
    fetch(
      `${process.env.NEXT_PUBLIC_LINK_TO_FETCH}/get-houses-for-sale?is_special=true`
    )
      .then((response) => response.json())
      .then((data) => {
        if (isMounted) {
          let sortedArray = sortArrayInDescendingOrder(
            data.specialHousesForSale
          );
          setSellingSpecialHouses(sortedArray);
        }
      });

    fetch(`${process.env.NEXT_PUBLIC_LINK_TO_FETCH}/get-jobs?is_special=true`)
      .then((response) => response.json())
      .then((data) => {
        if (isMounted) {
          let sortedArray = sortArrayInDescendingOrder(data.specialJobs);
          setSpecialJobs(sortedArray);
        }
      });
    return () => {
      isMounted = false;
    };
  }, []);

  return (
    <div className={styles.homepage_container}>
      <PageHeader
        title="Home Page | Listing Website"
        description="description"
        content="Generated by create next app"
        iconLink="/favicon.ico"
      />
      {specialJobs && (
        <DisplayListings
          containerTitle="Boosted Jobs"
          itemsToDisplay={specialJobs}
          amountOfItemsToDisplay={10}
          areWithoutImage={true}
          linkToPushTo="/jobs/"
        />
      )}
      {sellingSpecialHouses && (
        <DisplayListings
          containerTitle="Houses for Sale"
          itemsToDisplay={sellingSpecialHouses}
          amountOfItemsToDisplay={10}
          linkToPushTo="/for-sale/"
        />
      )}
    </div>
  );
}
